sudo: false
language: python
env:
  - TOXENV=py34-django18-test
  - TOXENV=py34-django19-test
  - TOXENV=py34-django110-test
  - TOXENV=py34-djangomaster-test
  - TOXENV=py34-isort
  - TOXENV=py34-flake
matrix:
  allow_failures:
    - env: TOXENV=py34-djangomaster-test
install:
  - pip install coveralls tox>=2.1
script:
  - tox
after_script:
  - coveralls
